dangerlet markersData ={
	'fireplace':{name: '火事場', icon: 'fire.PNG', distance:'300', color:'non'},
		'FireStation':{name: '消防署', icon: 'FireStation.png', distance:'300', color:'non'},
		
};

var data = [
	{  "id" : "danger_1",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_2",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_3",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_4",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_5",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_6",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_7",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_8",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_9",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_10",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_11",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_12",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_13",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_14",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_15",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_16",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_17",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_18",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_19",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_20",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_21",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_22",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_23",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_24",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_25",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_26",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_27",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_28",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_29",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_30",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_31",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_32",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_33",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_34",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_35",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_36",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_37",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_38",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_39",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_40",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_41",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_42",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_43",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_44",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_45",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_46",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_47",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_48",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_49",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
	{  "id" : "danger_50",  "cat" : "fireplace",  "name" : "",  "addr" : "",  "lat" : "",  "lon" : "",    },
    	
];
